#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(PSYSHOCK) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(VENOSHOCK) \
    F(TOXIC) \
    F(SNOWSCAPE) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(LEECH_LIFE) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(FLAME_CHARGE) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(LOW_SWEEP) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(ECHOED_VOICE) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(FOCUS_BLAST) \
    F(ENERGY_BALL) \
    F(OVERHEAT) \
    F(FALSE_SWIPE) \
    F(SCALD) \
    F(CHARGE_BEAM) \
    F(INCINERATE) \
    F(BRUTAL_SWING) \
    F(WILL_O_WISP) \
    F(SHADOW_CLAW) \
    F(PAYBACK) \
    F(SMART_STRIKE) \
    F(GIGA_IMPACT) \
    F(STONE_EDGE) \
    F(VOLT_SWITCH) \
    F(THUNDER_WAVE) \
    F(GYRO_BALL) \
    F(SWORDS_DANCE) \
    F(STRUGGLE_BUG) \
    F(BULLDOZE) \
    F(DARK_PULSE) \
    F(FROST_BREATH) \
    F(ACROBATICS) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(DRAGON_TAIL) \
    F(INFESTATION) \
    F(POISON_JAB) \
    F(GRASS_KNOT) \
    F(PLUCK) \
    F(U_TURN) \
    F(SUBSTITUTE) \
    F(FLASH_CANNON) \
    F(WILD_CHARGE) \
    F(SNARL) \
    F(NATURE_POWER) \
    F(POWER_UP_PUNCH) \
    F(DAZZLING_GLEAM) \
    F(ROOST) \
    F(AVALANCHE) \
    F(SMACK_DOWN) \
    F(PLAY_ROUGH) \
    F(MUD_SHOT) \
    F(DRAGON_PULSE) \
    F(DRAINING_KISS) \
    F(HEX) \
    F(HURRICANE) \
    F(CHARM) \
    F(HONE_CLAWS) \
    F(RETALIATE) \
    F(ROCK_POLISH) \
    F(ZEN_HEADBUTT) \
    F(CONFIDE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
