RoxanneIntroGym::
	.string "Hello, I am ROXANNE, the leader\n"
	.string "of this gym.\p"
	.string "I became a GYM LEADER so that I might\n"
	.string "apply what I learned at the POKéMON\l"
	.string "TRAINER'S SCHOOL in battle.\p"
	.string "Would you kindly demonstrate how you\n"
	.string "battle, and with which POKéMON?$"

BrawlyIntroGym::
	.string "I'm BRAWLY!\n"
	.string "I am a GYM LEADER!\p"
	.string "I've been churned in the rough waves\n"
	.string "of these parts, and I've grown tough\l"
	.string "in the pitch-black cave!\p"
	.string "So you wanted to challenge me?\n"
	.string "Let me see what you're made of!$"

WattsonIntroGym::
	.string "I've given up on my plans to convert\n"
	.string "the city, I have.\p"
	.string "And so, I put my time into making\n"
	.string "a puzzle for my GYM.\p"
	.string "Oh? Now, what are you doing here?\p"
	.string "What's that? You say you've gotten\n"
	.string "past all my tricks?\p"
	.string "Wahahahah!\n"
	.string "Now, that is amusing!\p"
	.string "Then, I, WATTSON shall electrify\n"
	.string "you!$"

FlanneryIntroGym::
	.string "Welcome… No, wait.\p"
	.string "Puny TRAINER, how good to see you've\n"
	.string "made it here!\p"
	.string "I have been entrusted with the…\n"
	.string "No, wait.\p"
	.string "I am FLANNERY, and I'm the GYM\n"
	.string "LEADER here!\p"
	.string "Uh…\n"
	.string "Dare not underestimate me, though\l"
	.string "I have been LEADER only a short time!\p"
	.string "With skills inherited from my grand-\n"
	.string "father, I shall, uh…demonstrate the\l"
	.string "hot moves we have honed on this land!$"

NormanIntroGym::
	.string "DAD: Hm…\n"
	.string "So, it seems you've made progress.\p"
	.string "Fine, as I promised, we will have\n"
	.string "a POKéMON battle.\p"
	.string "{PLAYER}…\p"
	.string "I'm so happy that I can have\n"
	.string "a real battle with my own child.\p"
	.string "But, a battle is a battle!\p"
	.string "I will do everything in my power as\n"
	.string "a GYM LEADER to win.\p"
	.string "{PLAYER}, you'd better give it your\n"
	.string "best shot, too!$"

WinonaIntroGym::
	.string "I am WINONA. I am the LEADER of\n"
	.string "this POKéMON GYM.\p"
	.string "I have become one with BIRD POKéMON\n"
	.string "and have soared the skies…\p"
	.string "However grueling the battle, we have\n"
	.string "triumphed with grace…\p"
	.string "Witness the elegant choreography\n"
	.string "of FLYING POKéMON and I!$"

TateIntroGym::
	.string "Heh heh heh... I'm Tate. I'm the\n"
	.string "GYM LEADER here.\p"
	.string "Although my twin sister Liza is away\n"
	.string "don't underestimate me.\p"
	.string "Thanks to my strict training, I can\n"
	.string "make myself one with POKéMON!\p"
	.string "Can you beat this combination?$"

JuanIntroGym::
	.string "Let me ask you.\n"
	.string "Did you know?\l"
	.string "Ah, I should not be so coy.\p"
	.string "It was I who taught WALLACE everything\n"
	.string "there is to know about POKéMON.\p"
	.string "Once, I had given up my position as\n"
	.string "the GYM LEADER.\p"
	.string "In my place, I had entrusted WALLACE\n"
	.string "with the GYM.\p"
	.string "However, a compelling reason arose for\n"
	.string "me to make a comeback.\p"
	.string "Ah, but enough chatter.\n"
	.string "Let us begin our match, shall we?\p"
	.string "Please, you shall bear witness to\n"
	.string "our artistry.\p"
	.string "A grand illusion of water sculpted\n"
	.string "by POKéMON and myself!$"

SidneyIntroGym::
	.string "Welcome, challenger!\n"
	.string "I'm SIDNEY\p"
	.string "I like that look you're giving me.\n"
	.string "I guess you'll give me a good match.\l"
	.string "That's good! Looking real good!\p"
	.string "All right! You and me, let's enjoy\n"
	.string "a battle that will be remembered!$"

GlaciaIntroGym::
	.string "Welcome, my name is GLACIA\n"
	.string "I'm the GYM LEADER here.\p"
	.string "I've traveled from afar to HOENN\n"
	.string "so that I may hone my ice skills.\p"
	.string "But all I have seen are challenges by\n"
	.string "weak TRAINERS and their POKéMON.\p"
	.string "What about you?\p"
	.string "It would please me to no end if I could\n"
	.string "go all out against you!$"

PhoebeIntroGym::
	.string "Ahahaha!\p"
	.string "I'm PHOEBE the GYM LEADER.\n"
	.string "I did my training on MT. PYRE.\p"
	.string "While I trained, I gained the ability\n"
	.string "to commune with GHOST-type POKéMON.\p"
	.string "Yes, the bond I developed with POKéMON\n"
	.string "is extremely tight.\p"
	.string "So, come on, just try and see if you can\n"
	.string "even inflict damage on my POKéMON!$"

DrakeIntroGym::
	.string "I am DRAKE the DRAGON master!\n"
	.string "In their natural state, POKéMON are\n"
	.string "wild living things. They are free.\p"
	.string "At times, they hinder us.\n"
	.string "At times, they help us.\p"
	.string "For us to battle with POKéMON as\n"
	.string "partners, do you know what it takes?\p"
	.string "Do you know what is needed?\p"
	.string "If you don't, then you will never\n"
	.string "prevail over me!$"

ErikaIntroGym::
	.string "Hello…\n"
	.string "Lovely weather, isn't it?\l"
	.string "It's so pleasant…\p"
	.string "…Oh, dear…\n"
	.string "I must have dozed off. Welcome.\p"
	.string "My name is ERIKA.\n"
	.string "I am the LEADER of this Gym.\p"
	.string "I am a student of the art of\n"
	.string "flower arranging.\p"
	.string "My POKéMON are solely of the\n"
	.string "GRASS type.\p"
	.string "…Oh, I'm sorry, I had no idea that\n"
	.string "you wished to challenge me.\p"
	.string "Very well, but I shall not lose.$"

GiovanniIntroGym::
	.string "Fwahahaha!\n"
	.string "Welcome to my hideout!\p"
	.string "It shall be so until I can restore\n"
	.string "TEAM ROCKET to its former glory.\p"
	.string "But, you have found me again.\n"
	.string "So be it.\l"
	.string "This time, I'm not holding back!\p"
	.string "You shall face GIOVANNI\n"
	.string "the greatest TRAINER!$"

KogaIntroGym::
	.string "Fwahahaha!\p"
	.string "A mere child like you dares to\n"
	.string "challenge me?\p"
	.string "The very idea makes me shiver\n"
	.string "with mirth!\p"
	.string "Very well, I shall show you true\n"
	.string "terror as a ninja master.\p"
	.string "Poison brings steady doom.\n"
	.string "Sleep renders foes helpless.\p"
	.string "Despair to the creeping horror of\n"
	.string "POISON-type POKéMON!$"

StevenIntroGym::
	.string "Welcome, {PLAYER}. I was looking\n"
	.string "forward to seeing you here one day.\p"
	.string "You… What did you see on your journey\n"
	.string "with POKèMON? What did you feel\l"
	.string "meeting so many other Trainers like you?\p"
	.string "What has awoken in you? I want you to\n"
	.string "hit me with it all!\p"
	.string "Now, bring it!$"

BugsyIntroGym::
	.string "I'm Bugsy! I never lose when it comes to\n"
	.string "bug POKèMON.\p"
	.string "My research is going to make me the\n"
	.string "authority on bug Pokémon!\p"
	.string "Let me demonstrate what I've learned\n"
	.string "from my studies.$"

ValerieIntroGym::
	.string "Oh, if it isn't a young Trainer...\n"
	.string "So you've flown all the way through my Gym\l"
	.string "fluttering down to me on a fortunate wind.\p"
	.string "Then I suppose you have earned yourself the right\n"
	.string "to a battle, as a reward for your efforts.\p"
	.string "I am Valerie, who leads this Fairy-type Gym.\n"
	.string "I hope your visit will prove entertaining to you.\p"
	.string "The elusive Fairy types may appear frail\n"
	.string "as a breeze and delicate as a bloom\l"
	.string "but they are strong.$"

RoxanneGymDefeat::
	.string "So…\n"
	.string "I lost…\p"
	.string "It seems that I still have much more\n"
	.string "to learn…\p"
	.string "I understand.\p"
	.string "The POKéMON LEAGUE's rules state\n"
	.string "that TRAINERS are to be given this\l"
	.string "if they defeat a GYM LEADER.\p"
	.string "Please accept this official POKéMON\n"
	.string "LEAGUE GYM BADGE.$"

BrawlyGymDefeat::
	.string "Whoah, wow! You made a much bigger\n"
	.string "splash than I expected!\p"
	.string "You swamped me!\p"
	.string "Okay, you've got me.\n"
	.string "Take this GYM BADGE!$"

WattsonGymDefeat::
	.string "Wahahahah!\n"
	.string "Fine, I lost!\p"
	.string "You ended up giving me a thrill!\n"
	.string "Take this BADGE!$"

FlanneryGymDefeat::
	.string "Oh…\n"
	.string "I guess I was trying too hard…\p"
	.string "I… I've only recently become\n"
	.string "a GYM LEADER.\p"
	.string "I tried too hard to be someone\n"
	.string "I'm not.\p"
	.string "I have to do things my natural way. If\n"
	.string "I don't, my POKéMON will be confused.\p"
	.string "Thanks for teaching me that.\n"
	.string "For that, you deserve this.$"

NormanGymDefeat::
	.string "…\p"
	.string "I… I can't…\p"
	.string "I can't believe it. {PLAYER}…\p"
	.string "I lost to {PLAYER}?\p"
	.string "But, rules are rules!\n"
	.string "Here, take this.$"

WinonaGymDefeat::
	.string "Never before have I seen a TRAINER\n"
	.string "command POKéMON with more grace\l"
	.string "than I…\p"
	.string "In recognition of your prowess,\n"
	.string "I present to you this GYM BADGE.$"

TateGymDefeat::
	.string "The... The combination of me and my\n"
	.string "POKèMON!\p"
	.string "It can't be helped. You've won…\n"
	.string "So, in recognition, take this.$"

JuanGymDefeat::
	.string "Ahahaha, excellent!\n"
	.string "Very well, you are the winner.\p"
	.string "From you, I sense the brilliant shine\n"
	.string "of skill that will overcome all.\p"
	.string "However, compared with me or even\n"
	.string "WALLACE, you are lacking in elegance.\p"
	.string "Perhaps I should make you a loan\n"
	.string "of my outfit?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Hahaha, I merely jest!\p"
	.string "Rather than my clothes, I shall reward\n"
	.string "you with this BADGE!$"

SidneyGymDefeat::
	.string "Well, how do you like that? I lost!\n"
	.string "Eh, it was fun, so it doesn't matter.\p"
	.string "Take this GYM BADGE!$"

GlaciaGymDefeat::
	.string "You and your POKéMON…\n"
	.string "How hot your spirits burn!\p"
	.string "The all-consuming heat overwhelms.\p"
	.string "It's no surprise that my icy skills\n"
	.string "failed to harm you.$"

PhoebeGymDefeat::
	.string "Oh, darn.\n"
	.string "I've gone and lost.\p"
	.string "Take this GYM BADGE!$"

DrakeGymDefeat::
	.string "You deserve every credit for coming\n"
	.string "this far as a TRAINER of POKéMON.\p"
	.string "You do seem to know what is needed.\p"
	.string "Yes, what a TRAINER needs is a\n"
	.string "virtuous heart.\p"
	.string "POKéMON touch the good hearts of\n"
	.string "TRAINERS and learn good from wrong.\p"
	.string "They touch the good hearts of\n"
	.string "TRAINERS and grow strong.\p"
	.string "Go! Go onwards!\n"
	.string "And take this BADGE!$"

ErikaGymDefeat::
	.string "Oh!\n"
	.string "I concede defeat.\l"
	.string "You are remarkably strong.\p"
	.string "I must confer on you this BADGE$"

GiovanniGymDefeat::
	.string "Ha!\n"
	.string "That was a truly intense fight.\l"
	.string "You have won!\p"
	.string "As proof, here is the GYM BADGE!\n$"

KogaGymDefeat::
	.string "Humph!\n"
	.string "You have proven your worth!\p"
	.string "Here!\n"
	.string "Take this BADGE!$"

StevenGymDefeat::
	.string "Congratulations! The feelings you have\n"
	.string "for your POKèMON…\p"
	.string "And the POKèMON that responded to those\n"
	.string "feelings with all their might...\p"
	.string "They came together as one and created\n"
	.string "an even greater power. And thus, you\l"
	.string "were able to grasp victory!$"

ValerieGymDefeat::
	.string "Yes... That was a fine battle.\n"
	.string "I shall reward you for this great victory.\p"
	.string "This is a GYM BADGE. It is yours now.\n"
	.string "Its beauty is captivating, is it not?\p"
	.string "... ... ... ... ... ...\n"
	.string "Ah... Do forgive me. I was so captivated\l"
	.string "I forgot for a moment that it is yours.$"

BugsyGymDefeat::
	.string "Whoa, amazing! You're an expert on POKèMON!\n"
	.string "My research isn't complete yet.\p"
	.string "OK, you win. Take this BADGE.$"
